add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/bc_diff)
add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/fshasher)
if (NOT UNLEASHED_RECOMP_SKIP_TARGET_TOOL_EXECUTABLES)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/file_to_c)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/x_decompress)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/XenonRecomp)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/XenosRecomp)
else()
    set(THIRDPARTY_ROOT ${UNLEASHED_RECOMP_TOOLS_ROOT}/XenonRecomp/thirdparty)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/XenonRecomp/thirdparty)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/XenonRecomp/XenonUtils)

    if (NOT TARGET libzstd)
        add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/XenosRecomp/thirdparty/zstd/build/cmake)
    endif()
endif()
if (NOT UNLEASHED_RECOMP_SKIP_TARGET_TOOL_EXECUTABLES)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/iso_extract)
    add_subdirectory(${UNLEASHED_RECOMP_TOOLS_ROOT}/xcontent_extract)
endif()
