name: Build Project

on:
  workflow_dispatch:
  push:
    branches:
      - linux-actions

env:
  FLATPAK_ID: io.github.hedge_dev.unleashedrecomp
  FREEDESKTOP_VERSION: 23.08
  LLVM_VERSION: 18

jobs:
  build-flatpak:
    name: Build Flatpak
    runs-on: ubuntu-24.04
    container:
        image: bilelmoussaoui/flatpak-github-actions:gnome-44
        options: --privileged
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ORG_TOKEN }}

      - name: Checkout private repository
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.ASSET_REPO }}
          token: ${{ secrets.ASSET_REPO_TOKEN }}
          path: flatpak/private

      - name: Install dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install -y ninja-build libsdl2-dev libgtk-3-dev

      - name: Prepare Flatpak
        run: |
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install -y flathub org.freedesktop.Sdk//${{env.FREEDESKTOP_VERSION}}
          flatpak install -y flathub org.freedesktop.Sdk.Extension.llvm${{env.LLVM_VERSION}}//${{env.FREEDESKTOP_VERSION}}

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@master
        with:
          bundle: ${{env.FLATPAK_ID}}.flatpak
          manifest-path: ./flatpak/${{env.FLATPAK_ID}}.json
          upload-artifact: false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UnleashedRecomp-flatpak
          path: ./${{env.FLATPAK_ID}}.flatpak